package tools

import (
	"context"
	"os"
	"strings"
	"testing"
	"time"

	"postgresql-mcp/internal/config"
	pgdb "postgresql-mcp/internal/db"
)

func TestPostgreSQLIntegration(t *testing.T) {
	if os.Getenv("POSTGRESQL_INTEGRATION_TEST") != "1" {
		t.Skip("set POSTGRESQL_INTEGRATION_TEST=1 to run against a disposable PostgreSQL database")
	}

	cfg, err := config.Load()
	if err != nil {
		t.Fatal(err)
	}
	cfg.AccessLevel = config.DDLRW
	cfg.QueryTimeout = 30 * time.Second
	cfg.MaxRowsDefault = 2
	cfg.RequireConfirmation = true
	client, err := pgdb.Open(cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = client.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	if err := client.DB.PingContext(ctx); err != nil {
		t.Fatal(err)
	}
	_, _ = client.Exec(ctx, "DROP SCHEMA IF EXISTS mcp_integration CASCADE")
	defer func() {
		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cleanupCancel()
		_, _ = client.Exec(cleanupCtx, "DROP SCHEMA IF EXISTS mcp_integration CASCADE")
	}()

	setup := []string{
		"CREATE SCHEMA mcp_integration",
		`CREATE TABLE mcp_integration.parent (
            a integer NOT NULL,
            b integer NOT NULL,
            payload jsonb,
            raw bytea,
            created_at timestamptz DEFAULT now(),
            total integer GENERATED ALWAYS AS (a + b) STORED,
            CONSTRAINT parent_key UNIQUE (a, b),
            CONSTRAINT positive_a CHECK (a > 0)
        )`,
		`CREATE TABLE mcp_integration.child (
            a integer,
            b integer,
            CONSTRAINT child_parent FOREIGN KEY (a, b) REFERENCES mcp_integration.parent (a, b)
        )`,
		`CREATE TABLE mcp_integration.atomic_insert (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            label text NOT NULL
        )`,
	}
	for _, statement := range setup {
		if _, err := client.Exec(ctx, statement); err != nil {
			t.Fatalf("setup %q: %v", firstWords(statement, 4), err)
		}
	}
	if _, err := client.Exec(ctx,
		"INSERT INTO mcp_integration.parent (a, b, payload, raw) VALUES ($1, $2, $3::jsonb, $4)",
		1, 2, `{"ok":true}`, []byte{0xff, 0x00}); err != nil {
		t.Fatal(err)
	}

	registry := &Registry{client: client}

	_, limited, err := registry.readData(ctx, nil, QueryInput{Query: "SELECT generate_series(1, 10) AS n LIMIT 8", MaxRows: 100})
	if err != nil {
		t.Fatal(err)
	}
	if len(limited.Rows) != cfg.MaxRowsDefault {
		t.Fatalf("read_data returned %d rows, want hard cap %d", len(limited.Rows), cfg.MaxRowsDefault)
	}

	_, parentRows, err := registry.readData(ctx, nil, QueryInput{Query: "SELECT payload, raw FROM mcp_integration.parent"})
	if err != nil {
		t.Fatal(err)
	}
	if len(parentRows.Rows) != 1 || parentRows.Rows[0]["raw"] != "/wA=" {
		t.Fatalf("unexpected binary result: %#v", parentRows.Rows)
	}
	if payload, ok := parentRows.Rows[0]["payload"].(map[string]any); !ok || payload["ok"] != true {
		t.Fatalf("JSON result was not decoded: %#v", parentRows.Rows[0]["payload"])
	}

	_, _, err = registry.readData(ctx, nil, QueryInput{Query: "SELECT nextval(pg_get_serial_sequence('mcp_integration.atomic_insert', 'id'))"})
	if err == nil {
		t.Fatal("read_data allowed a sequence mutation in its read-only transaction")
	}

	_, _, err = registry.insertData(ctx, nil, InsertInput{
		Table: "mcp_integration.atomic_insert",
		Rows: []map[string]any{
			{"label": "must roll back"},
			{"missing_column": "failure"},
		},
	})
	if err == nil {
		t.Fatal("insert_data should fail for an unknown column")
	}
	assertRowCount(t, ctx, client, "mcp_integration.atomic_insert", 0)

	_, inserted, err := registry.insertData(ctx, nil, InsertInput{
		Table: "mcp_integration.atomic_insert",
		Rows:  []map[string]any{{"label": "first"}, {"label": "second"}, {"label": "third"}},
	})
	if err != nil || inserted.RowsAffected != 3 {
		t.Fatalf("insert_data = %#v, %v", inserted, err)
	}

	update := WhereMutationInput{
		Table:  "mcp_integration.atomic_insert",
		Values: map[string]any{"label": "updated"},
		Where:  "label = $label",
		Params: map[string]any{"label": "first"},
	}
	_, preview, err := registry.updateData(ctx, nil, update)
	if err != nil || preview.Executed || len(preview.Preview) != 1 {
		t.Fatalf("update preview = %#v, %v", preview, err)
	}
	update.Confirm = true
	_, updated, err := registry.updateData(ctx, nil, update)
	if err != nil || !updated.Executed || updated.RowsAffected != 1 {
		t.Fatalf("update execution = %#v, %v", updated, err)
	}

	_, profile, err := registry.profileTable(ctx, nil, ProfileTableInput{Table: "mcp_integration.parent"})
	if err != nil {
		t.Fatal(err)
	}
	if !containsNamedRow(profile.Columns, "payload") || !containsNamedRow(profile.Columns, "raw") {
		t.Fatalf("profile omitted columns without MIN/MAX support: %#v", profile.Columns)
	}

	_, ddl, err := registry.showCreateTable(ctx, nil, TableInput{Table: "mcp_integration.parent"})
	if err != nil {
		t.Fatal(err)
	}
	for _, fragment := range []string{
		"DEFAULT now()", "GENERATED ALWAYS AS", `CONSTRAINT "parent_key" UNIQUE`, `CONSTRAINT "positive_a" CHECK`,
	} {
		if !strings.Contains(ddl.DDL, fragment) {
			t.Errorf("show_create_table omitted %q:\n%s", fragment, ddl.DDL)
		}
	}

	_, relationships, err := registry.inspectRelationships(ctx, nil, TableInput{Table: "mcp_integration.child"})
	if err != nil {
		t.Fatal(err)
	}
	if len(relationships.Outbound) != 2 || relationships.Outbound[0]["column"] != "a" ||
		relationships.Outbound[0]["referencedColumn"] != "a" || relationships.Outbound[1]["column"] != "b" ||
		relationships.Outbound[1]["referencedColumn"] != "b" {
		t.Fatalf("composite foreign key mapping is incorrect: %#v", relationships.Outbound)
	}

	_, described, err := registry.describeTable(ctx, nil, TableInput{Table: "mcp_integration.parent"})
	if err != nil {
		t.Fatal(err)
	}
	if len(described.Indexes) != 1 || !strings.Contains(described.Indexes[0]["definition"].(string), "parent_key") {
		t.Fatalf("index description is incomplete: %#v", described.Indexes)
	}
	_, sizes, err := registry.tableSize(ctx, nil, TableSizeInput{Table: "mcp_integration.parent"})
	if err != nil || len(sizes.Rows) != 1 || sizes.Rows[0]["table"] != "parent" {
		t.Fatalf("filtered table_size = %#v, %v", sizes.Rows, err)
	}
	_, dropPreview, err := registry.dropTable(ctx, nil, DropTableInput{Table: "mcp_integration.child"})
	if err != nil || dropPreview.Executed || len(dropPreview.Preview) != 1 {
		t.Fatalf("drop_table preview = %#v, %v", dropPreview, err)
	}

	if _, _, err := registry.explainQuery(ctx, nil, ExplainInput{Query: "SELECT * FROM mcp_integration.parent"}); err != nil {
		t.Fatalf("explain_query: %v", err)
	}
}

func assertRowCount(t *testing.T, ctx context.Context, client *pgdb.Client, table string, want int64) {
	t.Helper()
	rows, err := client.Query(ctx, "SELECT COUNT(*) AS count FROM "+table)
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) != 1 || rows[0]["count"] != want {
		t.Fatalf("row count = %#v, want %d", rows, want)
	}
}

func containsNamedRow(rows []map[string]any, name string) bool {
	for _, row := range rows {
		if row["name"] == name {
			return true
		}
	}
	return false
}

func firstWords(value string, count int) string {
	words := strings.Fields(value)
	if len(words) > count {
		words = words[:count]
	}
	return strings.Join(words, " ")
}
